# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

current_branch = `exists() { type -t "$1" > /dev/null 2>&1; } && if exists git; then git rev-parse --abbrev-ref HEAD; fi`.chop

target 'EZInteractiveNavigationSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EZInteractiveNavigationSample


  if current_branch == 'master'
    pod 'EZCustomNavigation', '1.0.0'
    else
    pod 'EZCustomNavigation', :path => '../EZCustomNavigation.podspec'
  end
end
